version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: /
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: /src/test/resources/hudson/plugins/sshslaves/agents
    schedule:
      interval: "daily"
